[project]
name = "padjective"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "openai>=1.59.5",
    "pandas>=2.2.3",
    "psycopg[binary]>=3.2.3",
    "pytest>=8.3.5",
    "scikit-learn>=1.6.1",
    "torch==2.7.*",
    "tqdm>=4.67.1",
]
[project.scripts]
tagbattle = "padjective.tagbattle:main"
ranking = "padjective.ranking:main"
display = "padjective.display:main"
product_synsets = "padjective.product_synsets:main"
taxonomy-classifier = "padjective.taxonomy_classifier:main"
taxonomy-classifier-schema = "padjective.taxonomy_classifier_schema:main"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

