"""Tests that download and validate real database dumps from datadumps.ifost.org.au."""

import os
import tempfile
from pathlib import Path
from urllib.request import urlopen
from urllib.error import URLError

import psycopg
import pytest


DATADUMPS_BASE_URL = "https://datadumps.ifost.org.au/padjective/"

# Core data files (required for basic functionality)
CORE_DUMPS = [
    "cantbuymelove_taxonomy.sql",
    "cantbuymelove_product.sql",
    "cantbuymelove_product_taxonomy.sql",
    "public_product_details.sql",
]

# Results files (generated by models)
RESULTS_DUMPS = [
    "padjective_battles.sql",
    "padjective_umllr_fold_metrics.sql",
    "padjective_umllr_tag_coefficients.sql",
    "padjective_umllr_predictions.sql",
    "padjective_umllr_taxonomy_encodings.sql",
    "padjective_dummy_fold_metrics.sql",
    "padjective_dummy_predictions.sql",
    "padjective_taxonomy_pclr_models.sql",
    "padjective_taxonomy_pclr_class_distribution.sql",
    "padjective_taxonomy_pclr_tag_summary.sql",
    "padjective_taxonomy_pclr_top_tags.sql",
    "padjective_taxonomy_pclr_fold_results.sql",
    "padjective_taxonomy_pclr_predictions.sql",
    "padjective_taxonomy_pclr_coefficients.sql",
    "padjective_taxonomy_nn_fold_results.sql",
    "padjective_taxonomy_nn_predictions.sql",
]


def download_dump(filename: str, cache_dir: Path) -> Path:
    """Download a SQL dump file if not already cached."""
    cached_path = cache_dir / filename

    if cached_path.exists():
        return cached_path

    url = f"{DATADUMPS_BASE_URL}{filename}"
    print(f"Downloading {url}...")

    try:
        with urlopen(url, timeout=30) as response:
            data = response.read()
            cached_path.write_bytes(data)
            return cached_path
    except URLError as e:
        pytest.skip(f"Could not download {filename}: {e}")


def load_dump_into_db(conn, dump_path: Path) -> None:
    """Load a SQL dump file into the database."""
    sql_content = dump_path.read_text(encoding="utf-8")

    with conn.cursor() as cur:
        cur.execute(sql_content)


@pytest.fixture(scope="session")
def cache_dir():
    """Provide a cache directory for downloaded dumps."""
    cache_path = Path(tempfile.gettempdir()) / "padjective_test_dumps"
    cache_path.mkdir(exist_ok=True)
    return cache_path


@pytest.fixture(scope="session")
def test_db_with_dumps(cache_dir):
    """Create a test database and load all dumps into it."""
    dsn = os.environ.get("SHOPIFY_DB_DSN")
    if not dsn:
        pytest.skip("SHOPIFY_DB_DSN environment variable not set")

    # Create test schemas
    with psycopg.connect(dsn, autocommit=True) as conn:
        with conn.cursor() as cur:
            cur.execute("DROP SCHEMA IF EXISTS cantbuymelove CASCADE")
            cur.execute("DROP SCHEMA IF EXISTS padjective CASCADE")
            cur.execute("DROP TABLE IF EXISTS public.product_details")

            cur.execute("CREATE SCHEMA cantbuymelove")
            cur.execute("CREATE SCHEMA padjective")

    # Download and load dumps
    all_dumps = CORE_DUMPS + RESULTS_DUMPS

    with psycopg.connect(dsn, autocommit=True) as conn:
        for dump_file in all_dumps:
            try:
                dump_path = download_dump(dump_file, cache_dir)
                print(f"Loading {dump_file}...")
                load_dump_into_db(conn, dump_path)
            except Exception as e:
                print(f"Warning: Failed to load {dump_file}: {e}")

    yield dsn

    # Cleanup not strictly necessary for test DB


@pytest.mark.slow
def test_dumps_are_accessible(cache_dir):
    """Test that we can download at least the core dumps."""
    for dump_file in CORE_DUMPS[:2]:  # Just test first 2 to be quick
        url = f"{DATADUMPS_BASE_URL}{dump_file}"
        try:
            with urlopen(url, timeout=10) as response:
                assert response.status == 200, f"Failed to access {url}"
                assert int(response.headers.get("Content-Length", 0)) > 0
        except URLError:
            pytest.skip(f"Could not access datadumps server")


@pytest.mark.slow
def test_core_data_integrity(test_db_with_dumps):
    """Validate that core data has been loaded correctly."""
    with psycopg.connect(test_db_with_dumps) as conn:
        with conn.cursor() as cur:
            # Check taxonomy table exists and has data
            cur.execute("SELECT COUNT(*) FROM cantbuymelove.taxonomy")
            taxonomy_count = cur.fetchone()[0]
            assert taxonomy_count > 0, "taxonomy table should have records"

            # Check product table exists and has data
            cur.execute("SELECT COUNT(*) FROM cantbuymelove.product")
            product_count = cur.fetchone()[0]
            assert product_count > 0, "product table should have records"

            # Check product_taxonomy linkage
            cur.execute("SELECT COUNT(*) FROM cantbuymelove.product_taxonomy")
            product_taxonomy_count = cur.fetchone()[0]
            assert product_taxonomy_count > 0, "product_taxonomy table should have records"

            # Check referential integrity
            cur.execute("""
                SELECT COUNT(*)
                FROM cantbuymelove.product_taxonomy pt
                LEFT JOIN cantbuymelove.product p ON p.id = pt.product_id
                WHERE p.id IS NULL
            """)
            orphaned_count = cur.fetchone()[0]
            assert orphaned_count == 0, "All product_taxonomy records should reference valid products"


@pytest.mark.slow
def test_taxonomy_structure(test_db_with_dumps):
    """Validate taxonomy data structure."""
    with psycopg.connect(test_db_with_dumps) as conn:
        with conn.cursor() as cur:
            # Check taxonomy has required columns
            cur.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = 'cantbuymelove'
                  AND table_name = 'taxonomy'
                ORDER BY ordinal_position
            """)
            columns = [row[0] for row in cur.fetchall()]
            assert "taxonomy_id" in columns
            assert "taxonomy_path" in columns

            # Check for non-null taxonomy_path values
            cur.execute("""
                SELECT COUNT(*)
                FROM cantbuymelove.taxonomy
                WHERE taxonomy_path IS NULL OR taxonomy_path = ''
            """)
            null_paths = cur.fetchone()[0]
            assert null_paths == 0, "All taxonomies should have valid paths"


@pytest.mark.slow
def test_battles_data(test_db_with_dumps):
    """Validate battles data exists."""
    with psycopg.connect(test_db_with_dumps) as conn:
        with conn.cursor() as cur:
            # Check battles table exists
            cur.execute("SELECT COUNT(*) FROM padjective.battles")
            battles_count = cur.fetchone()[0]
            assert battles_count > 0, "battles table should have records"

            # Check battles have winner and loser
            cur.execute("""
                SELECT COUNT(*)
                FROM padjective.battles
                WHERE winner_tag IS NULL OR loser_tag IS NULL
            """)
            invalid_battles = cur.fetchone()[0]
            assert invalid_battles == 0, "All battles should have winner and loser"


@pytest.mark.slow
def test_model_results_exist(test_db_with_dumps):
    """Check that model result tables exist and have data."""
    with psycopg.connect(test_db_with_dumps) as conn:
        with conn.cursor() as cur:
            # Check UMllr results
            cur.execute("SELECT COUNT(*) FROM padjective.umllr_fold_metrics")
            umllr_count = cur.fetchone()[0]
            assert umllr_count > 0, "UMllr fold metrics should exist"

            # Check Dummy classifier results
            cur.execute("SELECT COUNT(*) FROM padjective.dummy_fold_metrics")
            dummy_count = cur.fetchone()[0]
            assert dummy_count > 0, "Dummy fold metrics should exist"

            # Check PCLR results
            cur.execute("SELECT COUNT(*) FROM padjective.taxonomy_pclr_fold_results")
            lr_count = cur.fetchone()[0]
            assert lr_count > 0, "PCLR fold results should exist"

            # Check NN results
            cur.execute("SELECT COUNT(*) FROM padjective.taxonomy_nn_fold_results")
            nn_count = cur.fetchone()[0]
            assert nn_count > 0, "NN fold results should exist"


@pytest.mark.slow
def test_cv_folds_consistency(test_db_with_dumps):
    """Verify that CV folds are consistent across models."""
    with psycopg.connect(test_db_with_dumps) as conn:
        with conn.cursor() as cur:
            # Check that all models use the same fold count
            cur.execute("SELECT DISTINCT cv_fold FROM padjective.umllr_fold_metrics ORDER BY cv_fold")
            umllr_folds = [row[0] for row in cur.fetchall()]

            cur.execute("SELECT DISTINCT cv_fold FROM padjective.dummy_fold_metrics ORDER BY cv_fold")
            dummy_folds = [row[0] for row in cur.fetchall()]

            cur.execute("SELECT DISTINCT cv_fold FROM padjective.taxonomy_pclr_fold_results ORDER BY cv_fold")
            lr_folds = [row[0] for row in cur.fetchall()]

            cur.execute("SELECT DISTINCT cv_fold FROM padjective.taxonomy_nn_fold_results ORDER BY cv_fold")
            nn_folds = [row[0] for row in cur.fetchall()]

            # All should have the same folds (typically 0-4 for 5-fold CV)
            assert umllr_folds == dummy_folds, "UMllr and Dummy should use same folds"
            assert umllr_folds == lr_folds, "UMllr and PCLR should use same folds"
            assert lr_folds == nn_folds, "PCLR and NN should use same folds"
            assert len(umllr_folds) > 0, "Should have at least one fold"


@pytest.mark.slow
def test_product_details_filtered(test_db_with_dumps):
    """Verify product_details only contains products from cantbuymelove.product."""
    with psycopg.connect(test_db_with_dumps) as conn:
        with conn.cursor() as cur:
            # Check that all product_details rows match products
            cur.execute("""
                SELECT COUNT(*)
                FROM public.product_details pd
                LEFT JOIN cantbuymelove.product p ON
                    pd.myshopify_domain = p.myshopify_domain
                    AND pd.run_name = p.run_name
                    AND pd.product_handle = p.product_handle
                WHERE p.id IS NULL
            """)
            unmatched = cur.fetchone()[0]
            assert unmatched == 0, "All product_details should match cantbuymelove.product"
